### ISSUE TITLE
Label --label does not belong to COCO labels

### ISSUE THREAD

**Issue by ioeshu** [mdhmz1/Auto-Annotate#11]
getting this error:

Using TensorFlow backend.
WARNING:tensorflow:From annotate.py:14: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From annotate.py:14: The name tf.logging.ERROR is deprecated. Please use tf.compat.v1.logging.ERROR instead.

Traceback (most recent call last):
  File "annotate.py", line 141, in <module>
    assert args.label in class_names, "Label --label does not belong to COCO labels "
NameError: name 'class_names' is not defined

**Comment by mdhmz1** [comment]
Hey @ioeshu! Thanks for bringing this up. 
I have provided the fix. Hope this resolves the bug.

**Comment by tingfong99** [comment]
issue persist  
the error:  
  
Using TensorFlow backend.
WARNING:tensorflow:From annotate.py:14: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From annotate.py:14: The name tf.logging.ERROR is deprecated. Please use tf.compat.v1.logging.ERROR instead.

Traceback (most recent call last):
  File "annotate.py", line 156, in <module>
    assert args.label in COCO_DATASET_LABELS, "Label --label does not belong to COCO labels "
AssertionError: Label --label does not belong to COCO labels
