### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by jarleven** [mdhmz1/Auto-Annotate#13]
Issue is fixed by downgrading h5py. Maybe specify this version in the requirements.txt
pip install 'h5py==2.10.0' --force-reinstall

https://stackoverflow.com/questions/53740577/does-any-one-got-attributeerror-str-object-has-no-attribute-decode-whi

python3 annotate.py annotateCustom --image_directory=/host/Notes/SalmonModel --label=Salmon --weights=/host/mask_rcnn_coco_tf22_01082021/mask_rcnn_mmodel_0030.h5 --displayMaskedImages=True

Loading weights...  /host/mask_rcnn_coco_tf22_01082021/mask_rcnn_mmodel_0030.h5
Traceback (most recent call last):
  File "annotate.py", line 218, in <module>
    model.load_weights(weights_path, by_name=True)
  File "/Auto-Annotate/mrcnn/model.py", line 2130, in load_weights
    saving.load_weights_from_hdf5_group_by_name(f, layers)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py", line 3114, in load_weights_from_hdf5_group_by_name
    original_keras_version = f.attrs['keras_version'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'

**Comment by mdhmz1** [comment]
Thanks @jarleven for updating the workaround. I will create a page to capture these known issues which will be helpful for other folks. Thank you!!
