### ISSUE TITLE
Version Issue Tensorflow and keras 

### ISSUE THREAD

**Issue by subhash137** [mdhmz1/Auto-Annotate#30]
Code is written in tensorflow and keras version 1 . can you change the code to tensorflow 2 and also keras,
Due to this issue we cannot run code as tensorflow 1 is unable to download and use right now.

**Comment by subhash137** [comment]
please reply on this issue

**Comment by shivakarnati** [comment]
Hi @subhash137 did you solve this issue?

**Comment by subhash137** [comment]
nope
